"""
Singapore Smart City - Level 1 Trainer
YOLOv11s Knowledge Distillation Engine

This module executes the Teacher-Student distillation loop for the Perception layer.
Designed for cloud-native execution (AWS / Kaggle).
"""

import argparse
import os

from ultralytics import YOLO


def train_yolo_distillation(data_yaml: str, epochs: int, imgsz: int, batch_size: int, output_dir: str):
    """
    Executes the training sequence for the lightweight YOLOv11s model
    on the pseudo-labeled dataset generated by Grounding DINO + SAM.
    """
    print("🚀 Initializing Knowledge Distillation (YOLOv11s Student)...")

    # Ensure output directory exists
    os.makedirs(output_dir, exist_ok=True)

    # Load base small model
    model = YOLO("yolo11s.pt")

    # Execute heavily augmented training loop
    results = model.train(
        data=data_yaml,
        epochs=epochs,
        imgsz=imgsz,
        batch=batch_size,
        patience=15,

        # Optimizer and Schedule
        optimizer="AdamW",
        lr0=0.001,
        lrf=0.01,
        cos_lr=True,
        warmup_epochs=3.0,

        # Extreme Augmentations for Domain Robustness
        mosaic=1.0,
        close_mosaic=10,
        translate=0.2,
        scale=0.6,

        # MLOps
        project=output_dir,
        name="distilled_v1",
        cache=True
    )

    print(f"\n✅ Distillation complete! Weights saved to: {results.save_dir}")

    print("\n⚡ Compiling to INT8 TensorRT/ONNX for Edge Inference...")
    path = model.export(format="onnx", dynamic=True, simplify=True, int8=True)
    print(f"ONNX Graph saved: {path}")

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Level 1 Knowledge Distillation Trainer")
    parser.add_argument("--data", type=str, required=True, help="Path to data.yaml")
    parser.add_argument("--epochs", type=int, default=75)
    parser.add_argument("--imgsz", type=int, default=640)
    parser.add_argument("--batch", type=int, default=32)
    parser.add_argument("--output", type=str, default="models/level1/")

    args = parser.parse_args()

    print("Knowledge Distillation Trainer module is ready for cloud deployment.")
    # In a compute environment, we would invoke:
    # train_yolo_distillation(args.data, args.epochs, args.imgsz, args.batch, args.output)
